### ISSUE TITLE
Build error on Rust 1.33.0-nightly.

### ISSUE THREAD

**Issue by jordanmack** [lawliet89/rocket_cors#60]
There is a problem compiling on the newest Rust nightly. (rustc 1.33.0-nightly (d22fa2d87 2019-01-08))

```
   Compiling rocket_cors v0.4.0-rc.1 (https://github.com/lawliet89/rocket_cors#9cb16ba0)
error[E0254]: the name `log` is defined multiple times
   --> /home/jmack/.cargo/git/checkouts/rocket_cors-5d6823f67bcb0532/9cb16ba/src/lib.rs:591:24
    |
553 | extern crate log;
    | ----------------- previous import of the extern crate `log` here
...
591 | use log::{error, info, log};
    |                        ^^^ `log` reimported here
    |
    = note: `log` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
    |
591 | use log::{error, info, log as other_log};
    |                        ^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by lawliet89** [comment]
Can you try with version [`0.4.0`](https://crates.io/crates/rocket_cors/0.4.0) instead?

I just tried with `rust version 1.33.0-nightly (d22fa2d87 2019-01-08)` it was fine.

**Comment by jordanmack** [comment]
I had it pulling from git master, so I'm not sure what version I was using.

It seems to be working fine with 0.4.0.
